// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.25.0

package database

import (
	"time"

	"github.com/google/uuid"
)

type Project struct {
	ID            uuid.UUID
	CreatedAt     time.Time
	UpdatedAt     time.Time
	Name          string
	WalletAddress string
}

type User struct {
	ID            uuid.UUID
	CreatedAt     time.Time
	WalletAddress string
}

type Vote struct {
	ID        uuid.UUID
	CreatedAt time.Time
	UserID    uuid.UUID
	ProjectID uuid.UUID
	Value     int32
}
