version: '3.8'
services:
  indexer:
    build: ./
    restart: always
    environment:
      DB: postgres://root:password@db:5432/breadchain-indexer
      PORT: 8000
    depends_on:
      - db
    ports:
      - 8000:8000
  db:
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: password
      POSTGRES_DB: breadchain-indexer
    volumes:
      - ./data:/var/lib/postgresql/data
    ports:
      - 5432:5432

  caddy:
    image: caddy:latest
    restart: unless-stopped
    cap_add:
      - NET_ADMIN
    ports:
      - "80:80"
      - "443:443"
      - "443:443/udp"
    volumes:
      - $PWD/caddy/Caddyfile:/etc/caddy/Caddyfile
      - $PWD/caddy/site:/srv
      - caddy_data:/data
      - caddy_config:/config

volumes:
  caddy_data:
  caddy_config: