version: '3.8'
services:
  indexer:
    build: ./
    restart: always
    environment:
      DB_URL: postgres://root:password@indexer_db:5432/breadchain_indexer?sslmode=disable
      PORT: 8000
      VOTE_INTERVAL: 5
      SLICE_INTERVAL: 120
    depends_on:
      - indexer_db
    ports:
      - 8000:8000

  indexer_db:
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: password
      POSTGRES_DB: breadchain_indexer
    volumes:
      - ./dbdata:/var/lib/postgresql/data
    ports:
      - 5432:5432

  caddy:
    image: caddy:latest
    restart: unless-stopped
    cap_add:
      - NET_ADMIN
    ports:
      - "80:80"
      - "443:443"
      - "443:443/udp"
    volumes:
      - ./caddy/Caddyfile:/etc/caddy/Caddyfile
      - caddy_data:/data
      - caddy_config:/config

volumes:
  caddy_data:
  caddy_config:
